sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
script:
- mvn clean package
after_script:
- mvn generate-resources -Pdocs -Dmaven.test.skip=true
- mvn -q scm-publish:publish-scm -Pdocs -Dmaven.test.skip=true
env:
  global:
  - secure: PvbWAZrEA2nc9XoOq6hiSYlrnbyTtGnHGdFX5uREar9087wu2Jb2k+b/bUZcY2t5RE2g7IFV8IFG91SIJreq0mmHDhH4BHFQL9VIS1m/JZfmD2PFNMEfa2HI44p0kJeBsdbIGByfHabeGNIySSjeVD0SKqY7NfGYhAO2E17OS7IHW0sMm5VHm0HTMaxc/Rn2/0Xa8mDwgOaugJ4PWNLMf83fftR3bsCw5MY8853G0gWqyLAhEfN+sBzcN1VgZcfg+bFuqV3TEyN4BjI81ab7S6gsZ2/S8dFlig8whVR+eYcgGp6qDxVlAi2bs6op1YtwwPtibt0s6s0a+jBuJ7lvWSe7HS5+PUaJDZY36CYwM+Yc66Su2WnboggcfeHFZ2Bzvt3ElhHNCyyVtp32sWBolrelfFNj+xxy7Ux/HSniFhjzAKD9N3YQhnuTAy2HWXg86h4C/zKOCJyv7GrCfZ4KMJ6zG9UTPO2sOikGJ0uSrwPvPlbeNCxiraGIE7eJZL7sYWsuO+YkJwY61I4Mg3KFbbMknfaoztcR/TbTW7bCH17GKKFSemAYAiMUnDT/xHU/eD/Bw0Og96hfG9Ic2Gjy6F0llP6+xwLsdNqmmHtTgAM+lX48wfxxiADJgi0AjDPjp5/fqOl7gh8xyu8r6E4IjAWTC/u4pN+Ods0R5VL/sPc=
  - secure: cIlzXZ0gEsHxh1k3tThZhawB+CRfOx2Fdwk/CNco13wMGFEifzJEcL/QGsfhv7OGFAcdrPnv1RRH1drkVke/MwDOE/xqnjyzFegkzQ0azdLZOwujpX+Gl/OdHhnwgFyBJXHujNX6h02gkJhOD/cjv4rNuS1yQN8tGczzXeC/wATt644SaX8E/zU+o1RrX8QNoiYJB9/J5FumuwhNNTbfvb2cqMbNnfIW31cMToIINvJNRsXSK5ZUh0ZVWvbMmklsVNe7Vv2QlGYwoNKIG1xgPSzEnOyHBANILBuOkw4YI8kHD3f1c9VImBgrpUInZGyHaqQxAlb3cDicnNp5LSOynzS22dl/WoMqCNh/6YowTzKCgSJC8HmX4T8w4V4R2bJx8+4IkQhUNI/YfcGqlKNUqNo+0KXPKyrlWmYp2+G9lj6TMt6ht9pm0RpBFla9tu+zIc70Zr8EDGdVGnoDQ1VPExS1t/uFtC5wqEwNRyyjMwzLJoynuo/ZQ9WKRbAlcfLiM1K3F1EZ4jCkC+lbpKu9VWz21BBcDGExrHt4XUIV7t2MHGRwwe7FwLkuRLDFPjZNOK0cpd/Vw4RQALJqI6ecqp9QHHGoq6TMv8cZNl7piT+1MZybW9YS3owGFQD30segkeEw3DKG2kD6423IRbjjI7jMlKNYiE7hroG4pyXet0U=
